### ISSUE TITLE
needs better background music

### ISSUE THREAD

**Issue by SwadicalRag** [glua-team/glua-team.github.io#9]

**Comment by SwadicalRag** [comment]
- [ ] has music video
- [x] is really intimidating music
- [ ] fits in with the rebellious theme of glua.team
- [ ] music (video) contains no self harm
- [ ] slightly humorous to those viewing glua.team and implies the page is satirical

**Comment by ar1a** [comment]
https://www.youtube.com/watch?v=CSvFpBOe8eY

WAKEUP

WAKEUP

BIASDBUASDBUASDBASUDBASND MAKEUP

**Comment by Shigbeard** [comment]
I picked great music
https://github.com/glua-team/glua-team.github.io/pull/14

**Comment by bigdogmat** [comment]
Does this count as intimidating, https://www.youtube.com/watch?v=gZa4yre0uEk

**Comment by MDFL64** [comment]
https://www.youtube.com/watch?v=Gd9OhYroLN0

**Comment by SwadicalRag** [comment]
@Shigbeard 
- [ ] has music video
- [ ] is really intimidating music
- [ ] fits in with the rebellious theme of glua.team
- [x] music (video) contains no self harm
- [ ] slightly humorous to those viewing glua.team and implies the page is satirical

@bigdogmat 
- [x] has music video
- [ ] is really intimidating music
- [ ] fits in with the rebellious theme of glua.team
- [x] music (video) contains no self harm
- [x] slightly humorous to those viewing glua.team and implies the page is satirical

@birdbrainswagtrain 
- [x] has music video
- [x] is really intimidating music
- [x] fits in with the rebellious theme of glua.team
- [ ] music (video) contains no self harm
- [ ] slightly humorous to those viewing glua.team and implies the page is satirical

**Comment by Shigbeard** [comment]
https://www.youtube.com/watch?v=z48NmdWbquw

> Music video
> Is intimidating
> rebel!!!
> no self harm
> the cac bypasses dont stop coming and they dont stop coming and they 
> dont stop coming and they dont stop coming and they dont stop coming and 
> they dont stop coming and they dont stop coming and they dont stop 
> coming and they dont stop coming and they dont stop coming and they dont 
> stop coming and they dont stop coming

**Comment by MDFL64** [comment]
Obviously we select an intimidating / rebellious / humorous sang and then make our own music video. In DarkRP, of course.

**Comment by SwadicalRag** [comment]
nice memes

**Comment by moonexpr** [comment]
https://youtu.be/rtR63-ecUNo

**Comment by ThatLing** [comment]
https://youtu.be/EwTZ2xpQwpA

**Comment by SwadicalRag** [comment]
https://soundcloud.com/gabbobreaker/hatsune-miku-worlds-end-dancehall-rocketman-remix

**Comment by MDFL64** [comment]
https://www.youtube.com/watch?v=ulPgWVC08KI

**Comment by Kefta** [comment]
The current music is GREAT.

**Comment by MDFL64** [comment]
It makes me sad that we have to choose between memes and decent music. To be fair evengelion is a meme so this is a pretty good tradeoff.

**Comment by Noiwex** [comment]
darude sandstorm

**Comment by ThatLing** [comment]
https://youtu.be/4hHwFk7webA

**Comment by Shigbeard** [comment]
![http://img.ndlee.com/shigbeard/4s3lvbp.gif](http://img.ndlee.com/shigbeard/4s3lvbp.gif)

**Comment by TrixterTheTux** [comment]
HI SHIGBEARD I LOVE U

**Comment by meepen** [comment]
finally shigbeard is gone from our lives

**Comment by Noiwex** [comment]
Shitbeard

**Comment by Kefta** [comment]
This is also good https://www.youtube.com/watch?v=aPtQE4Rk6y0
